# Generated by Django 5.1 on 2024-08-25 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatapp.room'),
        ),
    ]
